version: "3"
services:
  middleware:
    build: . 
    command: npm run dev
    ports:
      - "8000:8000"
    depends_on:
      - database
    volumes:
      - ./src/middleware/server:/middleware/server
      - ./src/blockchain/build:/blockchain/build
    environment:
      - PG_HOST=database
      - PG_PORT=5432
      - PG_USER=postgres
      - PG_DATABASE=offchainer
      - WEBTHREE_HOST=localhost
  database:
    build: docker/database
