version: "3"
services:
  middleware:
    build: .
    command: npm run dev
    ports:
      - "8000:8000"
    depends_on:
      - database
    volumes:
      - ./src/middleware/server:/middleware/server
      - ./src/middleware/benchmarking:/middleware/benchmarking
      # - ./src/blockchain/build:/blockchain/build
    environment:
      - PG_HOST=database
      - PG_PORT=5432
      - PG_USER=postgres
      - PG_DATABASE=offchainer
      - WEBTHREE_HOST=ganache
      # - WEBTHREE_HOST=docker.for.mac.localhost
      # - WEBTHREE_HOST=10.0.2.2
      - WEBTHREE_PORT=7545
  database:
    build: docker/database
  ganache:
    build: docker/ganache
